server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: beaver-core-${ENV:local}

  cloud:
    gateway:
      routes:
        # Auth routes - no JWT validation, direct proxy to user-service
        - id: auth-routes
          uri: ${user-service.url}
          predicates:
            - Path=/users/auth/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
            - name: AddRequestHeader
              args:
                name: X-Service-Secret
                value: ${gateway.secret}
            - name: AddRequestHeader
              args:
                name: X-Source
                value: gateway

        # Protected user routes - JWT validation + context enrichment + strip prefix
        - id: user-service-protected
          uri: ${user-service.url}
          predicates:
            - Path=/users/**
          filters:
            - Authentication        # Step 1: Validate JWT
            - ContextEnrichment     # Step 2: Extract claims and add headers
            - name: StripPrefix
              args:
                parts: 1
            - name: AddRequestHeader
              args:
                name: X-Service-Secret
                value: ${gateway.secret}
            - name: AddRequestHeader
              args:
                name: X-Source
                value: gateway

        # Future tenant routes (placeholder)
        - id: tenant-service-protected
          uri: ${tenant-service.url:http://localhost:8082}
          predicates:
            - Path=/tenants/**
          filters:
            - Authentication        # Step 1: Validate JWT
            - ContextEnrichment     # Step 2: Extract claims and add headers
            - name: StripPrefix
              args:
                parts: 1
            - name: AddRequestHeader
              args:
                name: X-Service-Secret
                value: ${gateway.secret}
            - name: AddRequestHeader
              args:
                name: X-Source
                value: gateway

logging:
  level:
    com.beaver.core: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.handler.FilteringWebHandler: WARN

jwt:
  secret: ${JWT_SECRET}
  accessTokenValidity: ${JWT_ACCESS_VALIDITY}
  refreshTokenValidity: ${JWT_REFRESH_VALIDITY}
  authDisabled: false

gateway:
  secret: ${GATEWAY_SECRET}

# Downstream Services
user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}