server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: beaver-core-${ENV:local}

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${user-service.url}
          predicates:
            - Path=/v1/users/**
          filters:
            - AuthenticationFilter
            - UserContextFilter
            - name: StripPrefix
              args:
                parts: 1
            - name: AddRequestHeader
              args:
                name: X-Service-Secret
                value: ${gateway.secret}
            - name: AddRequestHeader
              args:
                name: X-Source
                value: gateway

logging:
  level:
    com.beaver.core: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.handler.FilteringWebHandler: WARN

jwt:
  secret: ${JWT_SECRET}
  accessTokenValidity: ${JWT_ACCESS_VALIDITY}
  refreshTokenValidity: ${JWT_REFRESH_VALIDITY}
  authDisabled: false

gateway:
  secret: ${GATEWAY_SECRET}

# Downstream Services
user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}