server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: beaver-core-${ENV:local}

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/v1/users/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
            - name: AddRequestHeader
              args:
                name: X-Service-Secret
                value: ${GATEWAY_SECRET}
            - name: AddRequestHeader
              args:
                name: X-Source
                value: gateway

  data:
    redis:
      url: ${REDIS_URL}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}   # 15 minutes
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION} # 24 hours
