server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: beaver-core-${ENV:local}

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/v1/users/**
          filters:
            - AuthenticationFilter
            - name: StripPrefix
              args:
                parts: 1
            - name: AddRequestHeader
              args:
                name: X-Service-Secret
                value: ${GATEWAY_SECRET:default-secret}
            - name: AddRequestHeader
              args:
                name: X-Source
                value: gateway

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

logging:
  level:
    com.beaver.core: DEBUG
    '[org.springframework.cloud.gateway]': TRACE

jwt:
  secret: ${JWT_SECRET:my-super-secret-jwt-key-for-development-only-please-change-in-production}
  validity: ${JWT_VALIDITY:20}  # 20 minutes
  authDisabled: ${JWT_AUTH_DISABLED:true}
